### PR TITLE
Exclude rejected

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/170)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/170)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/api/graphQL.js, line 100 at r1](https://reviewable.io/reviews/saltastro/tacprocess/170#-MVzA8Nt3cHvecz5YcMp:-MVzA8Nt3cHvecz5YcMq:b-3d54mk) ([raw file](https://github.com/saltastro/tacprocess/blob/22ed01e02f87e353a80645fcd0a7e65fb122ff26/src/api/graphQL.js#L100)):*
> ```JavaScript
> export function convertProposals(proposals, semester, partner){
>   if (!proposals.proposals){ return []}
>   return proposals.proposals.filter(proposal => proposal.status !== 'Rejected').map( proposal => {
> ```

Now the name of the function is wrong -- you are converting and filtering.

More importantly, assuming you are using this function everywhere, you end up with incorrect numbers on the statistics page, as rejected proposals should be counted as submitted proposals.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/170)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/messages/NoRejectedProposalMessage.js, line 3 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9ob8e9ghSWrPVTLiO:-MW9ob8e9ghSWrPVTLiP:b9vk2v9) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/components/messages/NoRejectedProposalMessage.js#L3)):*
> ```JavaScript
> import React from 'react'
> 
> const NoRejectProposalMessage = () => (
> ```

NoRejectedProposalMessage ---> NoRejectedProposalsMessage
___
*[src/components/messages/NoRejectedProposalMessage.js, line 7 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9oigqE1eBBwziRq7s:-MW9oigqE1eBBwziRq7t:b-pdocng) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/components/messages/NoRejectedProposalMessage.js#L7)):*
> ```JavaScript
>     <div className='notification'>
>       <div>
>         <p>Please note all rejected proposals are not included.</p>
> ```

Please note that rejected proposals are not included.
___
*[src/styles/messages/messages.css, line 39 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9ovl10Pj87DhqNa7b:-MW9ovl10Pj87DhqNa7c:bjwkxli) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/styles/messages/messages.css#L39)):*
> ```CSS
> }
> 
> .notification {
> ```

Might need some discussion.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/170)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/api/graphQL.js, line 100 at r1](https://reviewable.io/reviews/saltastro/tacprocess/170#-MVzA8Nt3cHvecz5YcMp:-MVzC9YH2jLcOwYimvyx:bfywzx0) ([raw file](https://github.com/saltastro/tacprocess/blob/22ed01e02f87e353a80645fcd0a7e65fb122ff26/src/api/graphQL.js#L100)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now the name of the function is wrong -- you are converting and filtering.

More importantly, assuming you are using this function everywhere, you end up with incorrect numbers on the statistics page, as rejected proposals should be counted as submitted proposals.
</blockquote></details>

Statistics now are all done on the back end not the front end the function i sonly used to get the proposals that needs to be displayed. to be exact
___
*[src/components/messages/NoRejectedProposalMessage.js, line 3 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9ob8e9ghSWrPVTLiO:-MW9y7xZ7P5pgPAYK_PU:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/components/messages/NoRejectedProposalMessage.js#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

NoRejectedProposalMessage ---> NoRejectedProposalsMessage
</blockquote></details>

Done.
___
*[src/components/messages/NoRejectedProposalMessage.js, line 7 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9oigqE1eBBwziRq7s:-MW9y8Li2Cbxtjp6GN-M:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/components/messages/NoRejectedProposalMessage.js#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Please note that rejected proposals are not included.
</blockquote></details>

Done.
___
*[src/styles/messages/messages.css, line 39 at r2](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9ovl10Pj87DhqNa7b:-MW9y9Us1_nNDzI6085E:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/da7cf63af6345df5e6299544844926da93aca52a/src/styles/messages/messages.css#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might need some discussion.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/170)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/styles/messages/messages.css, line 43 at r3](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9zSq_-SUikwAL4iG8:-MW9zSq_-SUikwAL4iG9:b-9aarty) ([raw file](https://github.com/saltastro/tacprocess/blob/e82d37510bfa1582c1b8226cef200fcd40c2887e/src/styles/messages/messages.css#L43)):*
> ```CSS
>   background: #cccccc;
>   font-size: 20px;
>   padding: 0.1em;
> ```

Using 0.4em might be safer.
___
*[src/styles/messages/messages.css, line 44 at r3](https://reviewable.io/reviews/saltastro/tacprocess/170#-MW9zLVJ4TJKJIQGt04X:-MW9zLVJ4TJKJIQGt04Y:bkf1whz) ([raw file](https://github.com/saltastro/tacprocess/blob/e82d37510bfa1582c1b8226cef200fcd40c2887e/src/styles/messages/messages.css#L44)):*
> ```CSS
>   font-size: 20px;
>   padding: 0.1em;
>   font-weight: bold;
> ```

I thought you didn't want bold text?

**Pull request merged**
