### PR TITLE
Liaison page complete

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/76)

### CODE REVIEW

**Comment by hettlage** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[src/App.js, line 24 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV26OPBxbxzV2FQt1Q:-LAV26OPBxbxzV2FQt1R:b-sla667) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/App.js#L24)):*
> ```JavaScript
> 	componentDidMount() {
> 		if (this.props.isAuthenticated) {
>       this.props.dispatch(actions.fetchUserData())
> ```

One might consider combining all the asynchronous actions into a single one, in order to avoid GUI being rendered with half-finished data.

---

*[src/App.js, line 51 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV2dBTAw4kVVSc76XM:-LAV2dBTAw4kVVSc76XN:b-fteeux) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/App.js#L51)):*
> ```JavaScript
> 	}
> 
>   LoadProposalsAndTargets = (semester, partner) => {
> ```

This is a function, so it should start with a lower-case letter.

---

*[src/actions/liaison-astronomer-actions.js, line 37 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV3QcGEHxdGqVC9tig:-LAV3QcGEHxdGqVC9tih:b-ljw5e7) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/actions/liaison-astronomer-actions.js#L37)):*
> ```JavaScript
>  * @params partners
>  */
> export default function submitProposalsLiaison(proposals, semester, partner){
> ```

As proposals is plural, but liaison is not, the naming suggests that you are only considering one liaison.

---

*[src/actions/liaison-astronomer-actions.js, line 50 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV3qUT9TYB4sPjifGs:-LAV3qUT9TYB4sPjifGt:br2a841) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/actions/liaison-astronomer-actions.js#L50)):*
> ```JavaScript
>       return;
>     }
>     dispatch(fetchProposals(semester, partner));
> ```

fetchProposals is asynchronous, isn't it? Then you probably should add an await.

---

*[src/reducers/proposals.js, line 189 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV4tpzEUmQ2CdzyhJ9:-LAV4tpzEUmQ2CdzyhJA:b-djskpa) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/reducers/proposals.js#L189)):*
> ```JavaScript
> 						}
> 					} 
> 						return p;
> ```

Wrong indentation. :)

---

*[src/util/proposal-changes.js, line 19 at r1](https://beta.reviewable.io/reviews/saltastro/tacprocess/76#-LAV5Vvv11J9WgkxQugF:-LAV5Vvv11J9WgkxQugG:b-lrewi2) ([raw file](https://github.com/saltastro/tacprocess/blob/27ec6fdce7dc3132ae2d64339a0de0902af3423b/src/util/proposal-changes.js#L19)):*
> ```JavaScript
> export const isLiaisonAstronomerChanged = (proposal, initProposals) => initProposals.some(p => {
>   if( p.proposalCode === proposal.proposalCode){
>     return (p.liaisonAstronomer === proposal.liaisonAstronomer)
> ```

Shouldn't that be '!=='? (Also, consider simplifying this into a single line: p.proposalCode === proposal.proposalCode && p.liaisonAstronomer !== proposal.liaisonAstronomer)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/tacprocess/76)*

**Comment by Eb-Zeero** [comment]
Reviewed 1 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: 6 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/tacprocess/76)*

**Comment by Eb-Zeero** [comment]
Reviewed 2 of 8 files at r1, 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/tacprocess/76)*

**Comment by hettlage** [comment]
Reviewed 3 of 8 files at r1, 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/tacprocess/76)*

**Pull request merged**
