### PR TITLE
Development

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)

### CODE REVIEW

**Comment by hettlage** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 106 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyFtf0XrY04bTNYux:-LAqyFtf0XrY04bTNYuy:bozrce6) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L106)):*
> ```JavaScript
>     //Expect the submitLiaisons function to be called once
>     expect(submitLiaisons.mock.calls.length).toBe(1);
>     //Expect the submitLiaisons function to be called with the correct proposal
> ```

This and the next test are obsolete, as they are implied by the test that submitLiaisons is called with proposals.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 112 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqycul19wrRuNh_ToR:-LAqycul19wrRuNh_ToS:bfb7wkf) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L112)):*
> ```JavaScript
>     //Expect the submitLiaisons function to be called with the correct proposals
>     expect(submitLiaisons.mock.calls[0][0]).toEqual(proposals)
>     //Expect the submitLiaisons function to be called with the correct proposals
> ```

Note that you are not really testing that only modified proposals are submitted.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 113 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyXup9HX7KZy0XxGz:-LAqyXup9HX7KZy0XxH-:b414rst) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L113)):*
> ```JavaScript
>     expect(submitLiaisons.mock.calls[0][0]).toEqual(proposals)
>     //Expect the submitLiaisons function to be called with the correct proposals
>     expect(submitLiaisons.mock.calls[0][0]).not.toEqual(initProposals)
> ```

This test seems obsolete.

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 1 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr1SQRBcNnJY3y1I0c:-LAr1SQRBcNnJY3y1I0d:bvxt0se) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L1)):*
> ```JavaScript
> import React from "react"
> ```

The tests beg the question whether perhaps table rows should be a component of their own.

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 122 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr-WXEC3jdUVcouusG:-LAr-WXEC3jdUVcouusH:bcqbnch) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L122)):*
> ```JavaScript
>     //Expect the setLiaison function to be called three times
>     expect(setLiaison.mock.calls.length).toBe(3)
>     //Expect the setLiaison function to be called with the incorrect username
> ```

That comment looks a bit odd - you are saying that you expect the code to do what it is not expected to do... :)

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 123 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqzW85Bb4u-9voBMz1:-LAqzW85Bb4u-9voBMz2:b8wh9yr) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L123)):*
> ```JavaScript
>     expect(setLiaison.mock.calls.length).toBe(3)
>     //Expect the setLiaison function to be called with the incorrect username
>     expect(setLiaison.mock.calls[1][0]).not.toBe(selectArray[2].username)
> ```

Isn't that test implied by your previous tests already?
It seems that you don't test that the third change submits the correct values.

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 134 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr0dT41tSkzi9uPA1b:-LAr0dT50cOE3qL5jKQc:bnhjmm0) ([raw file](https://github.com/saltastro/tacprocess/blob/ea34ac4929535fc5e6a7b81d18c68a50de518619/src/components/tables/__tests__/liaison-table.spec.js#L134)):*
> ```JavaScript
>       setLiaison= {setLiaison} />)
>       // Drop down exists
>       expect(wrapper.find('.setLiaison').exists()).toBe(true);
> ```

Arguably the class name should be the same for the dropdown menu and the checkbox; and you should check that there is a select/checkbox (with that class, if necessary).

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 158 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr-wN08Pb17ZXAV_Mm:-LAr-wN08Pb17ZXAV_Mn:b-ihlu7r) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L158)):*
> ```JavaScript
>     expect(requestSummary.mock.calls[1][2]).toBe(semester)
> 
>     wrapper.find('.file-download').at(1).simulate('click');
> ```

See my comments for the previous describe().

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by Eb-Zeero** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 26 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LArpIyW1TbjZzYVjro9:-LArpIyW1TbjZzYVjroA:bbthaxk) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L26)):*
> ```JavaScript
> const initProposals = [
>   {
>     proposalId: '',
> ```

by having empty init proposals you it will mean all your proposals are created and proposals are all new

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by chynamyerz** [comment]
Review status: 1 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 26 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LArpIyW1TbjZzYVjro9:-LAsFi9QBtMIw7ABw5hu:b-wrtri) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

by having empty init proposals you it will mean all your proposals are created and proposals are all new
</blockquote></details>

Initial proposal data updated. Thanks for noting that out.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 106 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyFtf0XrY04bTNYux:-LAsFtd4Aguhj3Pu1xz0:biyrr54) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This and the next test are obsolete, as they are implied by the test that submitLiaisons is called with proposals.
</blockquote></details>

Obsolete tests removed. Thanks for pointing that out.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 112 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqycul19wrRuNh_ToR:-LAsG23h0xpUvkEloyyT:b44r6nh) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note that you are not really testing that only modified proposals are submitted.
</blockquote></details>

Initial proposal data Resolved.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 113 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyXup9HX7KZy0XxGz:-LAsG5-E4QGhXq45P_lj:bioi54v) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L113)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test seems obsolete.
</blockquote></details>

Obsolete tests removed

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 1 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr1SQRBcNnJY3y1I0c:-LAsGFNUDkyNlabpPvxF:bb9ppay) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The tests beg the question whether perhaps table rows should be a component of their own.
</blockquote></details>

Noted and discussed. In fixing progress

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 122 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr-WXEC3jdUVcouusG:-LAsGPgh-4i5TSP7gZ0_:b-dlwl0f) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L122)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That comment looks a bit odd - you are saying that you expect the code to do what it is not expected to do... :)
</blockquote></details>

:) Obsolete test I guess. Resolved though by eliminating the tests repetition.

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 123 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqzW85Bb4u-9voBMz1:-LAsGfp7-YvdsK43m6Uo:bwcma81) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that test implied by your previous tests already?
It seems that you don't test that the third change submits the correct values.
</blockquote></details>

Tests repetition eliminated.

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 134 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr0dT41tSkzi9uPA1b:-LAsH0QFB3Kh-IZ9FjMl:byhmb42) ([raw file](https://github.com/saltastro/tacprocess/blob/ea34ac4929535fc5e6a7b81d18c68a50de518619/src/components/tables/__tests__/liaison-table.spec.js#L134)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Arguably the class name should be the same for the dropdown menu and the checkbox; and you should check that there is a select/checkbox (with that class, if necessary).
</blockquote></details>

I think they should. Noted and will be updated

---

*[src/components/tables/__tests__/liaison-table.spec.js, line 158 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAr-wN08Pb17ZXAV_Mm:-LAsGn817y9mBzOH3jY-:b-83od3n) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/tables/__tests__/liaison-table.spec.js#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comments for the previous describe().
</blockquote></details>

Noted

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by hettlage** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 106 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyFtf0XrY04bTNYux:-LAwY0Af-D0ezIlnqAuX:b-69q3gr) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L106)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Obsolete tests removed. Thanks for pointing that out.
</blockquote></details>

But the test which wasn't obsolete was the following one:

expect(submitLiaisons.mock.calls[0][0]).toEqual(proposals)

You should be testing that submitLiaisons is called with the correct array of proposals.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by chynamyerz** [comment]
Review status: 1 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 106 at r1](https://reviewable.io/reviews/saltastro/tacprocess/80#-LAqyFtf0XrY04bTNYux:-LAwamoe2yFO29IQ4yK6:b1b2st8) ([raw file](https://github.com/saltastro/tacprocess/blob/64f18a86635964877940fd235f016b3e53f3e8bd/src/components/pages/__tests__/liaison-page.spec.js#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But the test which wasn't obsolete was the following one:

expect(submitLiaisons.mock.calls[0][0]).toEqual(proposals)

You should be testing that submitLiaisons is called with the correct array of proposals.
</blockquote></details>

Please check the new commits 

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by hettlage** [comment]
Reviewed 9 of 10 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 60 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0Qgwp2gAvbuqru-hz:-LB0Qgwq5W9IdK5yJgby:b4iu0xn) ([raw file](https://github.com/saltastro/tacprocess/blob/e0da84c08b69c69982be7a426dad3617067a629b/src/components/pages/__tests__/liaison-page.spec.js#L60)):*
> ```JavaScript
> 
>   it("Should trigger the event with the correct proposals infomation", () => {
>     let expectedProposals = [
> ```

Better: let  expectedProposals = [proposals[0], proposals[1]]

---

*[src/components/selectors/LiaisonSelector.js, line 16 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0TeM46Ho3tBobwI7L:-LB0TeM46Ho3tBobwI7M:b-vqtoyw) ([raw file](https://github.com/saltastro/tacprocess/blob/36af7ff022a91b7557bb6f32d3ce2ec2e3cefc8e/src/components/selectors/LiaisonSelector.js#L16)):*
> ```JavaScript
> }
> 
> const LiaisonSelector = ({proposal, astronomers, setLiaison, initProposals, inputValue, canAssign}) => {
> ```

initProposals are unnecessary.

---

*[src/components/tables/tablesComponents/LiaisonTableRow.js, line 5 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0TwNF7NJMa6f9MEeO:-LB0TwNF7NJMa6f9MEeP:b-vk5zcc) ([raw file](https://github.com/saltastro/tacprocess/blob/e0da84c08b69c69982be7a426dad3617067a629b/src/components/tables/tablesComponents/LiaisonTableRow.js#L5)):*
> ```JavaScript
> import LiaisonSelector from '../../selectors/LiaisonSelector'
> 
> const LiaisonTableRow = ({proposal, initProposals, requestSummary, semester, setLiaison, astronomers, username, canAssign}) => (
> ```

initProposals is unnecessary

---

*[src/components/tables/tablesComponents/__tests__/liaison-table-row.spec.js, line 76 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0U7uN8O7PAT_wKnXz:-LB0U7uN8O7PAT_wKnY-:b6jv4ib) ([raw file](https://github.com/saltastro/tacprocess/blob/e0da84c08b69c69982be7a426dad3617067a629b/src/components/tables/tablesComponents/__tests__/liaison-table-row.spec.js#L76)):*
> ```JavaScript
>     //Expect the requestSummary function to be called once
>     expect(requestSummary.mock.calls.length).toBe(1)
>     //Expect the requestSummary function to be called with the correct semester
> ```

... with the correct proposal code

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by chynamyerz** [comment]
Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/components/pages/__tests__/liaison-page.spec.js, line 60 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0Qgwp2gAvbuqru-hz:-LB0d9PiC_X-wIdCAQ_Z:bulvua8) ([raw file](https://github.com/saltastro/tacprocess/blob/e0da84c08b69c69982be7a426dad3617067a629b/src/components/pages/__tests__/liaison-page.spec.js#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Better: let  expectedProposals = [proposals[0], proposals[1]]
</blockquote></details>

Done that way in the new commit

---

*[src/components/tables/tablesComponents/__tests__/liaison-table-row.spec.js, line 76 at r3](https://reviewable.io/reviews/saltastro/tacprocess/80#-LB0U7uN8O7PAT_wKnXz:-LB0cqcWBLF2JOBukFMx:bb94h9f) ([raw file](https://github.com/saltastro/tacprocess/blob/e0da84c08b69c69982be7a426dad3617067a629b/src/components/tables/tablesComponents/__tests__/liaison-table-row.spec.js#L76)):*
> with the correct proposal code
Corrected in the new commit

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Comment by hettlage** [comment]
Reviewed 1 of 10 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/80)*

**Pull request merged**
