### PR TITLE
Data loading

### PR DESCRIPTION
**Pull request by Eb-Zeero**
page display only when all the data is loaded

---
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)

### CODE REVIEW

**Comment by hettlage** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/App.js, line 113 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBV96ZN22dLYMBaDjPA:-LBV96ZN22dLYMBaDjPB:bwb0l3d) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/App.js#L113)):*
> ```JavaScript
> 		fetchTargetsError: state.targets.error,
> 		userError: state.user.error,
> 		astroError: state.user.error,
> ```

What is "astroError" - and I guess it is not state.user.error?

---

*[src/actions/AdminActions.js, line 68 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBV9pbS5H5sga44oIQ9:-LBV9pbS5H5sga44oIQA:b-6lr798) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/AdminActions.js#L68)):*
> ```JavaScript
> 		querySaltUsers().then( res =>
> 			{
> 				dispatch(fetchSaltUsersPass(convertSaltUsers(res.data.data)))
> ```

The convertSaltUsers method probably should be elsewhere. Same for convertTacMembers.

---

*[src/actions/data-actions.js, line 53 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVAs__8MBA5Af3J3bw:-LBVAs__8MBA5Af3J3bx:b-3jstit) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/data-actions.js#L53)):*
> ```JavaScript
>       await Promise.all([saltAstronomers, user, proposals, targets, allocations, tacMembers, saltUsers])
>         .then(data => {
>           dispatch(FetchSAPass(convertSA(data[0].data.data)))
> ```

FetchSAPass --> fetchSAPass

---

*[src/actions/proposalsActions.js, line 45 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVBOSWDONbsi0WU_ep:-LBVBOSWDONbsi0WU_eq:by781n) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/proposalsActions.js#L45)):*
> ```JavaScript
> 		queryProposals(semester, partner).then( res =>
> 			{
> 				dispatch(FetchProposalsPass(convertProposals(res.data.data, semester, partner), semester))
> ```

FetchProposalsPass --> fetchProposalsPass

convertProposals probably should not be here

---

*[src/actions/saltAstronomerActions.js, line 34 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVBrz15PAJ_byJ6Tua:-LBVBrz2ER-9vCOEb_d8:b-xpn24l) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/saltAstronomerActions.js#L34)):*
> ```JavaScript
> }
> 
> export function convertSA(sa){
> ```

This probably should not be here.

---

*[src/actions/targetsActions.js, line 34 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVCOqICcGrRvnqxVdR:-LBVCOqICcGrRvnqxVdS:bbxyk91) ([raw file](https://github.com/saltastro/tacprocess/blob/84a45170d9dab400dcfd3033c104ce686fef1525/src/actions/targetsActions.js#L34)):*
> ```JavaScript
> }
> 
> function convertTargets(targets){
> ```

This arguably should not be here.

---

*[src/actions/timeAllocationActions.js, line 59 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVCeUC9CzOqTmipcI-:-LBVCeUC9CzOqTmipcI0:b-xpn24l) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/timeAllocationActions.js#L59)):*
> ```JavaScript
> });
> 
> export const convertPartnerAllocations = (data) => {
> ```

This probably should not be here.

---

*[src/components/messages/FailToLoad.js, line 10 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVD5nUBGMPXLGeKkDw:-LBVD5nUBGMPXLGeKkDx:b-jfd8hb) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/components/messages/FailToLoad.js#L10)):*
> ```JavaScript
>         </div>
>       <div>
>         <h2>Fail to load data please reload</h2>
> ```

<h2>Oops. Data download failed.</h2>
<p>The data needed for populating this page could not be downloaded. Please try again, or <a href="salthelp@salt.ac.za">contact SALT</a>.</p>

---

*[src/reducers/data.js, line 1 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVEL-5CJUpUBgcZE4m:-LBVEL-5CJUpUBgcZE4n:bnwdfxx) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/reducers/data.js#L1)):*
> ```JavaScript
> import {
> ```

I think the naming is unfortunate as this is about status more than data.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)*

**Comment by Eb-Zeero** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/App.js, line 113 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBV96ZN22dLYMBaDjPA:-LBVOJEJ1Z7hVFpSh0EE:b25a6jk) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/App.js#L113)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What is "astroError" - and I guess it is not state.user.error?
</blockquote></details>

this is not used anyway

---

*[src/actions/AdminActions.js, line 68 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBV9pbS5H5sga44oIQ9:-LBVOP1vCcOn1zR2Qy-B:b-q1wcq5) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/AdminActions.js#L68)):*
>  convertSaltUsers
all will be moved

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)*

**Comment by Eb-Zeero** [comment]
Review status: 17 of 27 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/components/messages/FailToLoad.js, line 10 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVD5nUBGMPXLGeKkDw:-LBWHZUU5_z-IlF04fKW:b-fng4kx) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/components/messages/FailToLoad.js#L10)):*
> Oops. Data download failed.
considered

---

*[src/reducers/data.js, line 1 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVEL-5CJUpUBgcZE4m:-LBWHeIT1HU9Y51NassE:b-w47c4j) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/reducers/data.js#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the naming is unfortunate as this is about status more than data.
</blockquote></details>

considered

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)*

**Comment by Eb-Zeero** [comment]
Review status: 17 of 27 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/actions/data-actions.js, line 53 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVAs__8MBA5Af3J3bw:-LBWOccHE9bYebTe_R-u:b-hff6wv) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/data-actions.js#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

FetchSAPass --> fetchSAPass
</blockquote></details>

renamed

---

*[src/actions/proposalsActions.js, line 45 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVBOSWDONbsi0WU_ep:-LBWOSSACF_SPiJ9Otl4:b-hff6wv) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/proposalsActions.js#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

FetchProposalsPass --> fetchProposalsPass

convertProposals probably should not be here
</blockquote></details>

renamed

---

*[src/actions/saltAstronomerActions.js, line 34 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVBrz15PAJ_byJ6Tua:-LBWOVEc-kOhQyrglRQl:b-40er1d) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/saltAstronomerActions.js#L34)):*
> renamed

---

*[src/actions/targetsActions.js, line 34 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVCOqICcGrRvnqxVdR:-LBWOYPjDdEUr0dnSYJv:b-hff6wv) ([raw file](https://github.com/saltastro/tacprocess/blob/84a45170d9dab400dcfd3033c104ce686fef1525/src/actions/targetsActions.js#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This arguably should not be here.
</blockquote></details>

renamed

---

*[src/actions/timeAllocationActions.js, line 59 at r1](https://reviewable.io/reviews/saltastro/tacprocess/82#-LBVCeUC9CzOqTmipcI-:-LBWOZgw8qG4vziRoRBp:b-w47c4j) ([raw file](https://github.com/saltastro/tacprocess/blob/ff44dea014ce3e498670c9361d17e2973aff8a81/src/actions/timeAllocationActions.js#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This probably should not be here.
</blockquote></details>

considered

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)*

**Comment by hettlage** [comment]
Reviewed 10 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/82)*

**Pull request merged**
