### PR TITLE
Add empty table and sort them. Fix buttons alignment

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq0oXa6S34sFcuDO7E:-MCq0oXa6S34sFcuDO7F:b-fv5y00) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
> ```JavaScript
> 
> 	comparePartners = (a, b) => {
> 		const partnerA = a.value.toUpperCase()
> ```

Wouldn't it make sense to swap partnerA <---> a and partnerB <---> b?
___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1lv0DBcMEs2YVpCr:-MCq1lv0DBcMEs2YVpCs:b-1nm3au) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
> ```JavaScript
> 
> 	comparePartners = (a, b) => {
> 		const partnerA = a.value.toUpperCase()
> ```

See comment for line 170 as well.
___
*[src/components/pages/TimeAllocationPage.js, line 124 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCptfQI2GtuiI9CONUC:-MCptfQJ4Fx4ucoXhnug:blhoetc) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L124)):*
> ```JavaScript
> 		const partnerB = b.value.toUpperCase()
> 
> 		let comparison = 0
> ```

You don't need a comparison variable if you just return the 1 and -1 straight away. :)
___
*[src/components/pages/TimeAllocationPage.js, line 170 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1bST-GM9p2G9KU60:-MCq1bST-GM9p2G9KU61:b-qw35q9) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L170)):*
> ```JavaScript
> 	    <div>
> 	      {
> 	        tac.submiting ? (<div><h1>Submitting...</h1></div>) : partners.sort(this.comparePartners).map(part => {
> ```

I think you should map from partner to value before sorting.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq0oXa6S34sFcuDO7E:-MF0PWSBC61cUMTNke5Z:b-y1e4lu) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it make sense to swap partnerA <---> a and partnerB <---> b?
</blockquote></details>

if what I had was just a string then I would not need the compareParner method.
I can only pass an object
___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1lv0DBcMEs2YVpCr:-MF0PwRnDrxG0tnrtx_a:bcduliq) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment for line 170 as well.
</blockquote></details>

if I follow what you said on 170 then I will have to go thougt an array all more than 2 times as I am doing now
which is map( =>[str]).sort( => [str]).map(=>JSX)
___
*[src/components/pages/TimeAllocationPage.js, line 124 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCptfQI2GtuiI9CONUC:-MF0Dnn16A44xSkuwOgj:bia0tk) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't need a comparison variable if you just return the 1 and -1 straight away. :)
</blockquote></details>

they can be equal , I need a 0 
___
*[src/components/pages/TimeAllocationPage.js, line 170 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1bST-GM9p2G9KU60:-MF0QJo10itFx-QSc6Xx:b-4fb9uu) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should map from partner to value before sorting.
</blockquote></details>

this was not going to work if the current map need another atribute from partner.
this way is good case we need to add atribute to partner.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq0oXa6S34sFcuDO7E:-MF0aS6z7HldHP9zB3b5:bwvruhl) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

if what I had was just a string then I would not need the compareParner method.
I can only pass an object
</blockquote></details>

I think you misunderstood me. My point was merely that "partnerA" is a more meaningful name than "a", and as such it would make more sense to have "partnerA" as the parameter name and "a" as the local variable.
___
*[src/components/pages/TimeAllocationPage.js, line 124 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCptfQI2GtuiI9CONUC:-MF0b20R4FpQvg2mPZLc:b-h2fe9e) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L124)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

they can be equal , I need a 0 
</blockquote></details>

But you could just say:

```
if (partnerA > partnerB) {
    return 1;
} else if (partnerA < partnerB) {
    return -1;
}
return 0;
```
___
*[src/components/pages/TimeAllocationPage.js, line 170 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1bST-GM9p2G9KU60:-MF0d0ra0pLj87MriR7R:bf0uhju) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L170)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this was not going to work if the current map need another atribute from partner.
this way is good case we need to add atribute to partner.

</blockquote></details>

But partners is not a list of partners; it is a list of objects {label, value}.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/components/pages/TimeAllocationPage.js, line 121 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq0oXa6S34sFcuDO7E:-MF5JkIFEALu6Thk_HBi:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you misunderstood me. My point was merely that "partnerA" is a more meaningful name than "a", and as such it would make more sense to have "partnerA" as the parameter name and "a" as the local variable.
</blockquote></details>

Done.
___
*[src/components/pages/TimeAllocationPage.js, line 124 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCptfQI2GtuiI9CONUC:-MF5JmeN0Tvj34P21b0J:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you could just say:

```
if (partnerA > partnerB) {
    return 1;
} else if (partnerA < partnerB) {
    return -1;
}
return 0;
```
</blockquote></details>

Done.
___
*[src/components/pages/TimeAllocationPage.js, line 170 at r1](https://reviewable.io/reviews/saltastro/tacprocess/148#-MCq1bST-GM9p2G9KU60:-MF5Kem53pOGzo4FcSVq:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/ce9c5cc452172845b7678d6a87500b4b92cd0c2e/src/components/pages/TimeAllocationPage.js#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But partners is not a list of partners; it is a list of objects {label, value}.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/148)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
