### PR TITLE
Hot fix

### PR DESCRIPTION
**Pull request by Eb-Zeero**
no test provided for semesterArray

---
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)

### CODE REVIEW

**Comment by hettlage** [comment]
The comment "no test provided for semesterArray" begs the question why not...? :-)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/util/filters.js, line 73 at r1](https://reviewable.io/reviews/saltastro/tacprocess/85#-LC9gd126z_MOA5jcW0s:-LC9gd126z_MOA5jcW0t:bb1ks1s) ([raw file](https://github.com/saltastro/tacprocess/blob/9258e73e788157611e633dc759a07c031c61532b/src/util/filters.js#L73)):*
> ```JavaScript
> 	const year = today.getFullYear();
> 	const semesters = [];
> 	while (startYear < year + 8){
> ```

I think +8 is a bit excessive... :-)

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LC9h2TM199VjBQylstW:b1m524h)*

**Comment by hettlage** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)*

**Comment by Eb-Zeero** [comment]
It was done before without test test and I only did little modification I will create a test for it 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/util/filters.js, line 73 at r1](https://reviewable.io/reviews/saltastro/tacprocess/85#-LC9gd126z_MOA5jcW0s:-LCZ1-Bt8NlT6fDZ6nKV:b-mvb0ak) ([raw file](https://github.com/saltastro/tacprocess/blob/9258e73e788157611e633dc759a07c031c61532b/src/util/filters.js#L73)):*
>  begs the question why not...? :-)
how many years should I add from the current year

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LCZ1Nrc20ADRqOGn2xf:bkksmnd)*

**Comment by hettlage** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/util/filters.js, line 73 at r1](https://reviewable.io/reviews/saltastro/tacprocess/85#-LC9gd126z_MOA5jcW0s:-LCZ3kt7EOdrBpI9hXW8:b5vzv3e) ([raw file](https://github.com/saltastro/tacprocess/blob/9258e73e788157611e633dc759a07c031c61532b/src/util/filters.js#L73)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

>  begs the question why not...? :-)
how many years should I add from the current year

</blockquote></details>

I think 2 years is enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)*

**Comment by hettlage** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LCZ3vRyDIcfxyF5PMh8:bnfp4nl)*

**Comment by hettlage** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/util/__test__/filters.spec.js, line 9 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChi6bJ4xflL0gJJxr2:-LChi6bJ4xflL0gJJxr3:b-6uh59r) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L9)):*
> ```JavaScript
> 	
> 	it('Admins and SAs should have the same semesters', () => {
> 		expect(semestersArray([{type: ADMINISTRATOR}])).toEqual(semestersArray([{type: SALT_ASTRONOMER}]));
> ```

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).

---

*[src/util/__test__/filters.spec.js, line 12 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChibum8N1IHMQ8ycyw:-LChibum8N1IHMQ8ycyx:b-6uh59r) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L12)):*
> ```JavaScript
> 	});
> 	it('Tac chair and TAC members should have the same semesters', () => {
> 		expect(semestersArray([{type: TAC_MEMBER}])).toEqual(semestersArray([{type: TAC_CHAIR}]));
> ```

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).

---

*[src/util/__test__/filters.spec.js, line 15 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChilguDC4pS81Yqd9b:-LChilguDC4pS81Yqd9c:b-6uh59r) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L15)):*
> ```JavaScript
> 	});
> 	it('should have at least 2016-1 for admins', () => {
> 		expect(semestersArray([{type: ADMINISTRATOR}])).toContain("2016-1")
> ```

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).

---

*[src/util/__test__/filters.spec.js, line 18 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChimvq5CGstr9fLojb:-LChimvq5CGstr9fLojc:b-6uh59r) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L18)):*
> ```JavaScript
> 	});
> 	it('should not have 2016-1 for Tac chair and members', () => {
> 		expect(semestersArray([{type: TAC_CHAIR}, {type: TAC_MEMBER}])).not.toContain("2016-1");
> ```

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).

---

*[src/util/__test__/filters.spec.js, line 20 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChir9FEsqNyvI0VS3Y:-LChir9FEsqNyvI0VS3Z:b-hvcuyh) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L20)):*
> ```JavaScript
> 		expect(semestersArray([{type: TAC_CHAIR}, {type: TAC_MEMBER}])).not.toContain("2016-1");
> 	});
> 	it('should have at least 2018-1 and 2020-2 if date is 04/01/2018 for ADMINs and SAs', () => {
> ```

You should test that the correct array is returned.

---

*[src/util/__test__/filters.spec.js, line 29 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChj5wi5WOT93FAeFUv:-LChj5wi5WOT93FAeFUw:bofhyxt) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L29)):*
> ```JavaScript
> 		expect(semestersArray([{type: TAC_CHAIR}]).sort()).toEqual(["2017-2", "2018-1"])
> 	});
> 	it('should only have 2018-1 if date is 05/01/2018 for Tac chair and members', () => {
> ```

You should test (more) edge cases.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)*

**Comment by hettlage** [comment]
Thanks for adding the uni tests.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LChjJ2N-u4ACG856HfJ:b-7o4a7y)*

**Comment by Eb-Zeero** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

---

*[src/util/__test__/filters.spec.js, line 9 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChi6bJ4xflL0gJJxr2:-LEya6mFBtcYgaZxvC0Y:bntv4u9) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).
</blockquote></details>

file removed

---

*[src/util/__test__/filters.spec.js, line 12 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChibum8N1IHMQ8ycyw:-LEya5yO9_3HGJV0-Rw8:bntv4u9) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).
</blockquote></details>

file removed

---

*[src/util/__test__/filters.spec.js, line 15 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChilguDC4pS81Yqd9b:-LEya5M80RAY49E_lX67:bntv4u9) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).
</blockquote></details>

file removed

---

*[src/util/__test__/filters.spec.js, line 18 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChimvq5CGstr9fLojb:-LEya4hq4IWqx0nx5R-2:bntv4u9) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test might be unnecessary. Also, it relies on the current date, which should be avoided (read: mock it, as you do elsewhere).
</blockquote></details>

file removed

---

*[src/util/__test__/filters.spec.js, line 20 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChir9FEsqNyvI0VS3Y:-LEya43l6rh7xCdiP3XH:b-dznmyl) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L20)):*
> file removed
file removed

---

*[src/util/__test__/filters.spec.js, line 29 at r3](https://reviewable.io/reviews/saltastro/tacprocess/85#-LChj5wi5WOT93FAeFUv:-LEya0uI3wY506nvQL8a:bntv4u9) ([raw file](https://github.com/saltastro/tacprocess/blob/902544e0760627891ff4782d68c77c5cb7427d09/src/util/__test__/filters.spec.js#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should test (more) edge cases.
</blockquote></details>

file removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)*

**Comment by Eb-Zeero** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)*

**Comment by hettlage** [comment]
I'm puzzled - which file did you remove?

---

Review status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LF0aqF6-Q37ei4dgKgF:bv57v7f)*

**Comment by Eb-Zeero** [comment]
src/util/__test__/filters.spec.js.
tests in in were unnecessary 

---

Review status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85#-:-LF1XuNVD5F5oHgQS2Ah:btupokl)*

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/85)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
