### PR TITLE
added current semester to none admins 

### PR DESCRIPTION
**Pull request by Eb-Zeero**
tac members could not not see current semester but default semester
now it is all possible

---
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)

### CODE REVIEW

**Comment by hettlage** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---

*[src/util/index.js, line 405 at r1](https://reviewable.io/reviews/saltastro/tacprocess/83#-LBv6UaN49MS50dd_P3S:-LBv6UaO8PSmeal3v-oG:bp89338) ([raw file](https://github.com/saltastro/tacprocess/blob/5eb3050697db0c7eded04b64c7ed9df3ae6889e7/src/util/index.js#L405)):*
> ```JavaScript
> 
> /**
>  * A default semester is a semester which is 3 month ahead of the current semester.
> ```

is a semester ---> is the semester

3 month --->3 months

---

*[src/util/index.js, line 416 at r1](https://reviewable.io/reviews/saltastro/tacprocess/83#-LBv6jvz2W4miB3QRsA3:-LBv6jvz2W4miB3QRsA4:b7jlek) ([raw file](https://github.com/saltastro/tacprocess/blob/5eb3050697db0c7eded04b64c7ed9df3ae6889e7/src/util/index.js#L416)):*
> ```JavaScript
>     if (month >= 2 && month <=7) {
>     	semester = 1;
> 	} else if (month >= 8 && month <= 12) {
> ```

month <= 12 is redundant

---

*[src/util/index.js, line 439 at r1](https://reviewable.io/reviews/saltastro/tacprocess/83#-LBv79je6sdhwVaeBlfo:-LBv79je6sdhwVaeBlfp:b7jlek) ([raw file](https://github.com/saltastro/tacprocess/blob/5eb3050697db0c7eded04b64c7ed9df3ae6889e7/src/util/index.js#L439)):*
> ```JavaScript
> 	if (month >= 5 && month <=10) {
> 		semester = 1;
> 	} else if (month >= 11 && month <= 12) {
> ```

month <= 12 is redundant

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)*

**Comment by hettlage** [comment]
Reviewed 2 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)*

**Comment by hettlage** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)*

**Comment by Eb-Zeero** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/util/index.js, line 416 at r1](https://reviewable.io/reviews/saltastro/tacprocess/83#-LBv6jvz2W4miB3QRsA3:-LBv8p8rEpR9Dzs4obK4:bikq2d3) ([raw file](https://github.com/saltastro/tacprocess/blob/5eb3050697db0c7eded04b64c7ed9df3ae6889e7/src/util/index.js#L416)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

month <= 12 is redundant
</blockquote></details>

:)) it did not take me long to notice it  not it is fine

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)*

**Comment by hettlage** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/83)*

**Pull request merged**
