### PR TITLE
fix tac member fail to view pages.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 8 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114RnUBNaxElWMmhVi:-M114RnVAx9diii55D9q:b-mhulsy) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L8)):*
> ```JavaScript
> const PartnerSummaryStatTableRow1 = ({ partnerSummaryStat, totalObservation }) => {
>   if (partnerSummaryStat == null || Object.keys(partnerSummaryStat).length === 0) return null
>   console.log({partnerSummaryStat})
> ```

log statement should be removed
___
*[src/util/partner-stat.js, line 18 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114fDWAeudklS4rtDc:-M114fDWAeudklS4rtDd:b-bhv8ec) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/util/partner-stat.js#L18)):*
> ```JavaScript
> 
>   const allCompletionStats = completionStats.find(c => c.partner.toUpperCase() === 'ALL')
>     if (allCompletionStats === undefined) return undefined
> ```

There might be two spaces too many in front of the "if".

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 8 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114RnUBNaxElWMmhVi:-M143peL0axHBZLi4F54:bn19z5z) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

log statement should be removed
</blockquote></details>

sorry gone
___
*[src/util/partner-stat.js, line 18 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114fDWAeudklS4rtDc:-M143fwtCLd5wB5Uraal:b-q7rah9) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/util/partner-stat.js#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There might be two spaces too many in front of the "if".
</blockquote></details>

No, it is just one space

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/util/partner-stat.js, line 18 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114fDWAeudklS4rtDc:-M14cIbtCxs5CKxtHPHh:b-heuv7x) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/util/partner-stat.js#L18)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

No, it is just one space
</blockquote></details>

I beg to differ. The indentation of the if is too large.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/util/partner-stat.js, line 18 at r1](https://reviewable.io/reviews/saltastro/tacprocess/142#-M114fDWAeudklS4rtDc:-MF0BP2O0_UKm9483Hjg:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/0a7bd0f562d3ba5f7ee0ec3ea3b7753232764c12/src/util/partner-stat.js#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I beg to differ. The indentation of the if is too large.
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/142)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Pull request merged**
