### PR TITLE
Logout user when unauthorised

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/App.js, line 54 at r1](https://reviewable.io/reviews/saltastro/tacprocess/158#-MHWcpXZ0cB8gT7EMbU_:-MHWcpXZ0cB8gT7EMbUa:b8gc3eo) ([raw file](https://github.com/saltastro/tacprocess/blob/96a117ac9adbd2a6b20e052682df7772c5a0ce90/src/App.js#L54)):*
> ```JavaScript
> 
> 		if (dataStatus.error && !dataStatus.fetchedData){
> 			if (dataStatus.error === 'Request failed with status code 401'){
> ```

You are relying on an error message you do;t have control over. It would be safer to rely on the status code. See https://stackoverflow.com/questions/39153080/how-can-i-get-the-status-code-from-an-http-error-in-axios.
___
*[src/components/messages/FailToLoad.js, line 11 at r1](https://reviewable.io/reviews/saltastro/tacprocess/158#-MHWbDpv9kiTG1h5qxZn:-MHWbDpv9kiTG1h5qxZo:bh6blxf) ([raw file](https://github.com/saltastro/tacprocess/blob/96a117ac9adbd2a6b20e052682df7772c5a0ce90/src/components/messages/FailToLoad.js#L11)):*
> ```JavaScript
>       <div>
>         <h2>Oops. Data download failed.</h2>
>         <h2>Please refresh the page and login again. </h2>
> ```

... and, if necessary, login again ...

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/App.js, line 54 at r1](https://reviewable.io/reviews/saltastro/tacprocess/158#-MHWcpXZ0cB8gT7EMbU_:-MHjl8w85DDy8fsX2TvH:bolyric) ([raw file](https://github.com/saltastro/tacprocess/blob/96a117ac9adbd2a6b20e052682df7772c5a0ce90/src/App.js#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are relying on an error message you do;t have control over. It would be safer to rely on the status code. See https://stackoverflow.com/questions/39153080/how-can-i-get-the-status-code-from-an-http-error-in-axios.
</blockquote></details>

See now

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/App.js, line 54 at r1](https://reviewable.io/reviews/saltastro/tacprocess/158#-MHWcpXZ0cB8gT7EMbU_:-MIPBac99kGPvClJBxsc:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/96a117ac9adbd2a6b20e052682df7772c5a0ce90/src/App.js#L54)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

See now
</blockquote></details>

Done.
___
*[src/components/messages/FailToLoad.js, line 11 at r1](https://reviewable.io/reviews/saltastro/tacprocess/158#-MHWbDpv9kiTG1h5qxZn:-MIPB_az5xYDdt6dyC3Z:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/96a117ac9adbd2a6b20e052682df7772c5a0ce90/src/components/messages/FailToLoad.js#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

... and, if necessary, login again ...
</blockquote></details>

Done.

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/messages/FailToLoad.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/158#-MJRNKnR5uROLgQFUgZQ:-MJRNKnR5uROLgQFUgZR:b-oohpl5) ([raw file](https://github.com/saltastro/tacprocess/blob/5d5001e56e896a381eb8666aba103d6c987702d1/src/components/messages/FailToLoad.js#L11)):*
> ```JavaScript
>       <div>
>         <h2>Oops. Data download failed.</h2>
>         <h2>Please refresh the page and, if necessary, login again  </h2>
> ```

login again ---> login again. [full stop missing]
___
*[src/components/messages/FailToLoad.js, line 12 at r3](https://reviewable.io/reviews/saltastro/tacprocess/158#-MJRNbSr0MKTF_NkihKi:-MJRNbSr0MKTF_NkihKj:b-3jg9v) ([raw file](https://github.com/saltastro/tacprocess/blob/5d5001e56e896a381eb8666aba103d6c987702d1/src/components/messages/FailToLoad.js#L12)):*
> ```JavaScript
>         <h2>Oops. Data download failed.</h2>
>         <h2>Please refresh the page and, if necessary, login again  </h2>
>         <h2>If this message persist please contact SALT help.</h2>
> ```

persist ---> persists

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/components/messages/FailToLoad.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/158#-MJRNKnR5uROLgQFUgZQ:-MJVzj4N13hPgRtaPyrD:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/5d5001e56e896a381eb8666aba103d6c987702d1/src/components/messages/FailToLoad.js#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

login again ---> login again. [full stop missing]
</blockquote></details>

Done.
___
*[src/components/messages/FailToLoad.js, line 12 at r3](https://reviewable.io/reviews/saltastro/tacprocess/158#-MJRNbSr0MKTF_NkihKi:-MJVzisuDyGzqDxAm_0D:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/5d5001e56e896a381eb8666aba103d6c987702d1/src/components/messages/FailToLoad.js#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

persist ---> persists
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/158)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
