### PR TITLE
TAC Member issue fixing

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/159)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/159)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/util/partner-stat.js, line 20 at r1](https://reviewable.io/reviews/saltastro/tacprocess/159#-MJRIsT85EhADl4Qr1ZK:-MJRIsT9-YsGhEjqD4dW:b-r9iakv) ([raw file](https://github.com/saltastro/tacprocess/blob/ecf748d9204b342bbce08209ae189e4639f7729a/src/util/partner-stat.js#L20)):*
> ```JavaScript
>     .find(c => c.partner.toUpperCase() === 'ALL')
>   if (allCompletionStats){
>     allCompletionStats = allCompletionStats.summary.observedTime
> ```

It might be clearer to use a new variable instead of redefining allCompletionStats.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/159)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/partner-stat.js, line 20 at r1](https://reviewable.io/reviews/saltastro/tacprocess/159#-MJRIsT85EhADl4Qr1ZK:-MJVzFMGDvHEI-uzx8An:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/ecf748d9204b342bbce08209ae189e4639f7729a/src/util/partner-stat.js#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be clearer to use a new variable instead of redefining allCompletionStats.
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/159)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/159)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
